apiVersion: v1
kind: Secret

metadata:
  name: {{ include "efftest.secretName" . }}
  labels:
  {{- include "efftest.labels" . | nindent 4}}

type: Opaque

stringData:
  DB_USER: {{ .Values.postgres.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}

