name: Go CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "features/**"

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with: 
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run checks
        run: make check 

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2